"""Adaptateur Postgres (Supabase) — imite l'API sqlite3 que consomme repositories.py.

Backend optionnel pour une future version web ; le bureau reste sur SQLite (db.py).
Aucun module existant n'est modifié : `PgConnection` reproduit exactement le contrat
utilisé par le code appelant — execute(sql, params) avec des `?`, lastrowid, fetchone/
fetchall/rowcount, commit(), et `with conn:` au sens sqlite3 (commit/rollback SANS
fermer la connexion — le `with` d'une connexion psycopg3 native, lui, FERME).

Particularités absorbées ici :
- `prepare_threshold=None` obligatoire : le pooler Supabase en mode transaction ne
  supporte pas les prepared statements côté serveur (sinon « prepared statement does
  not exist » après 5 exécutions).
- `end` est un mot réservé Postgres (colonnes sessions.end et constraints.end) :
  chaque SQL est réécrit `\bend\b` → `"end"` (les identifiants end_at / end_date ne
  sont pas touchés, aucun littéral SQL du projet ne contient ce mot).
- `INSERT` sans RETURNING reçoit ` RETURNING id` pour alimenter lastrowid — sauf pour
  les tables sans colonne id (settings, schema_version).
- PRAGMA user_version est remplacé par une table schema_version à une seule ligne.
"""

from __future__ import annotations

import os
import re
from pathlib import Path

import psycopg
from dotenv import load_dotenv

# Traduction du script de db.py :
#   id INTEGER PRIMARY KEY -> IDENTITY ; REAL -> DOUBLE PRECISION (REAL = float4 en
#   Postgres, ce qui arrondirait les coefficients) ; le reste est identique, les dates
#   restent en TEXT ISO comme sur SQLite.
MIGRATIONS_PG: list[str] = [
    """
    CREATE TABLE IF NOT EXISTS courses (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        code TEXT NOT NULL,
        title TEXT NOT NULL,
        term TEXT NOT NULL,
        institution TEXT,
        credits INTEGER,
        instructor TEXT,
        language TEXT NOT NULL DEFAULT 'fr',
        difficulty INTEGER NOT NULL DEFAULT 3 CHECK (difficulty BETWEEN 1 AND 5),
        effort_multiplier DOUBLE PRECISION NOT NULL DEFAULT 1.0,
        archived INTEGER NOT NULL DEFAULT 0,
        UNIQUE (code, term)
    );

    CREATE TABLE IF NOT EXISTS sessions (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
        kind TEXT NOT NULL,
        weekday INTEGER NOT NULL CHECK (weekday BETWEEN 0 AND 6),
        start TEXT NOT NULL,
        end TEXT NOT NULL,
        room TEXT,
        start_date TEXT,
        end_date TEXT,
        except_dates TEXT NOT NULL DEFAULT '[]'
    );

    CREATE TABLE IF NOT EXISTS evaluations (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
        external_id TEXT NOT NULL,
        title TEXT NOT NULL,
        type TEXT NOT NULL,
        weight DOUBLE PRECISION NOT NULL,
        due_at TEXT,
        start_date TEXT,
        duration_minutes INTEGER,
        modality TEXT,
        location TEXT,
        cumulative INTEGER,
        group_work INTEGER,
        content_scope TEXT NOT NULL DEFAULT '[]',
        scope_units INTEGER,
        deliverable TEXT,
        estimated_pages INTEGER,
        resources TEXT NOT NULL DEFAULT '[]',
        notes TEXT,
        confidence TEXT NOT NULL DEFAULT 'high',
        source_excerpt TEXT,
        manual_hours_override DOUBLE PRECISION,
        status TEXT NOT NULL DEFAULT 'active',
        archived INTEGER NOT NULL DEFAULT 0,
        UNIQUE (course_id, external_id)
    );

    CREATE TABLE IF NOT EXISTS constraints (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        label TEXT NOT NULL,
        category TEXT NOT NULL,
        weekday INTEGER CHECK (weekday BETWEEN 0 AND 6),
        specific_date TEXT,
        start TEXT NOT NULL,
        end TEXT NOT NULL,
        rrule TEXT,
        priority INTEGER NOT NULL DEFAULT 0,
        color TEXT,
        CHECK ((weekday IS NULL) != (specific_date IS NULL))
    );

    CREATE TABLE IF NOT EXISTS generations (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        created_at TEXT NOT NULL,
        params_hash TEXT NOT NULL,
        coverage DOUBLE PRECISION,
        deficit_total DOUBLE PRECISION
    );

    CREATE TABLE IF NOT EXISTS study_blocks (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        evaluation_id INTEGER NOT NULL REFERENCES evaluations(id) ON DELETE CASCADE,
        start_at TEXT NOT NULL,
        end_at TEXT NOT NULL,
        planned_minutes INTEGER NOT NULL,
        status TEXT NOT NULL DEFAULT 'planned',
        locked INTEGER NOT NULL DEFAULT 0,
        generation_id INTEGER REFERENCES generations(id),
        actual_minutes INTEGER,
        efficiency DOUBLE PRECISION,
        note TEXT
    );

    CREATE TABLE IF NOT EXISTS settings (
        key TEXT PRIMARY KEY,
        value TEXT NOT NULL
    );

    CREATE INDEX IF NOT EXISTS idx_evaluations_course ON evaluations(course_id);
    CREATE INDEX IF NOT EXISTS idx_blocks_evaluation ON study_blocks(evaluation_id);
    CREATE INDEX IF NOT EXISTS idx_blocks_start ON study_blocks(start_at);
    """,
]

SCHEMA_VERSION_PG = len(MIGRATIONS_PG)

# Tables sans colonne id : ne jamais leur ajouter RETURNING id.
_NO_ID_TABLES = ("settings", "schema_version")

_END_WORD = re.compile(r"\bend\b", re.IGNORECASE)
_INSERT_TABLE = re.compile(r"^\s*INSERT\s+INTO\s+([A-Za-z_]+)", re.IGNORECASE)


def _translate(sql: str) -> str:
    """`?` -> `%s` et `end` (mot réservé) -> `\"end\"`."""
    return _END_WORD.sub('"end"', sql.replace("?", "%s"))


class _CursorProxy:
    """Le sous-ensemble de l'API curseur sqlite3 que le projet consomme."""

    def __init__(self, cursor, lastrowid: int | None = None):
        self._cursor = cursor
        self.lastrowid = lastrowid

    def fetchone(self):
        return self._cursor.fetchone()

    def fetchall(self):
        return self._cursor.fetchall()

    def __iter__(self):
        return iter(self._cursor)

    @property
    def rowcount(self) -> int:
        return self._cursor.rowcount


class PgConnection:
    """Connexion psycopg habillée en sqlite3.Connection (contrat de repositories.py)."""

    def __init__(self, raw: psycopg.Connection):
        self._conn = raw

    def execute(self, sql: str, params=()) -> _CursorProxy:
        sql_pg = _translate(sql)
        lastrowid = None
        cursor = self._conn.cursor()
        match = _INSERT_TABLE.match(sql_pg)
        wants_id = (
            match is not None
            and match.group(1).lower() not in _NO_ID_TABLES
            and "returning" not in sql_pg.lower()
        )
        if wants_id:
            cursor.execute(sql_pg + " RETURNING id", params)
            row = cursor.fetchone()
            lastrowid = row[0] if row else None
        else:
            cursor.execute(sql_pg, params)
        return _CursorProxy(cursor, lastrowid)

    def executescript(self, sql: str) -> None:
        # psycopg3 accepte plusieurs instructions dans un execute sans paramètres.
        self._conn.cursor().execute(_translate(sql))

    def commit(self) -> None:
        self._conn.commit()

    def rollback(self) -> None:
        self._conn.rollback()

    def close(self) -> None:
        self._conn.close()

    # `with conn:` au sens sqlite3 : commit/rollback, connexion laissée OUVERTE.
    # (Déléguer au __enter__/__exit__ psycopg fermerait la connexion à la sortie.)
    def __enter__(self) -> PgConnection:
        return self

    def __exit__(self, exc_type, _exc, _tb) -> bool:
        if exc_type is None:
            self.commit()
        else:
            self.rollback()
        return False


# Clé du verrou consultatif de migration (constante arbitraire, propre au projet).
_MIGRATION_LOCK_KEY = 1347240270  # 0x504C414E, « PLAN »


def migrate_pg(conn: PgConnection) -> None:
    """Applique les migrations manquantes ; schema_version remplace PRAGMA user_version.

    Sûr en concurrence : un verrou consultatif transactionnel (pg_advisory_xact_lock,
    compatible avec le pooler en mode transaction, contrairement au verrou de session)
    sérialise les migrants, et la version est relue APRÈS l'obtention du verrou — le
    second arrivant voit le schéma déjà à jour et n'applique rien.
    """
    with conn:
        conn.execute("SELECT pg_advisory_xact_lock(?)", (_MIGRATION_LOCK_KEY,))
        # Contrainte mono-ligne : une double insertion concurrente échoue proprement
        # (violation de clé primaire) au lieu de créer une deuxième ligne.
        conn.execute(
            "CREATE TABLE IF NOT EXISTS schema_version ("
            " id INTEGER PRIMARY KEY CHECK (id = 1),"
            " version INTEGER NOT NULL)"
        )
        # La table peut préexister sous son ancienne forme (version seule, sans id) :
        # la recréer sous verrou en préservant la version courante.
        has_id = conn.execute(
            "SELECT count(*) FROM information_schema.columns"
            " WHERE table_schema = current_schema()"
            " AND table_name = 'schema_version' AND column_name = 'id'",
        ).fetchone()[0]
        if not has_id:
            row = conn.execute("SELECT version FROM schema_version").fetchone()
            preserved = row[0] if row else 0
            conn.execute("DROP TABLE schema_version")
            conn.execute(
                "CREATE TABLE schema_version ("
                " id INTEGER PRIMARY KEY CHECK (id = 1),"
                " version INTEGER NOT NULL)"
            )
            conn.execute(
                "INSERT INTO schema_version (id, version) VALUES (1, ?)", (preserved,)
            )
        row = conn.execute("SELECT version FROM schema_version WHERE id = 1").fetchone()
        current = row[0] if row else 0
        if row is None:
            conn.execute("INSERT INTO schema_version (id, version) VALUES (1, 0)")
        for number, script in enumerate(MIGRATIONS_PG[current:], start=current + 1):
            conn.executescript(script)
            conn.execute("UPDATE schema_version SET version = ? WHERE id = 1", (number,))


def connect_pg(url: str | None = None, migrate: bool = True) -> PgConnection:
    """Ouvre (et migre par défaut) la base Postgres.

    Sans `url`, DATABASE_URL est lue depuis l'environnement, complété par le .env du
    dépôt via python-dotenv. `prepare_threshold=None` est OBLIGATOIRE avec le pooler
    Supabase en mode transaction.

    `migrate=False` saute migrate_pg — à utiliser sur le chemin chaud d'une API où le
    schéma est déjà en place (économise deux allers-retours par connexion) ; la
    migration se fait alors une fois au démarrage du service ou en déploiement.
    """
    if url is None:
        load_dotenv(Path(__file__).resolve().parents[3] / ".env")
        load_dotenv()  # .env du répertoire courant, le cas échéant
        url = os.environ.get("DATABASE_URL")
        if not url:
            raise RuntimeError(
                "DATABASE_URL introuvable : la définir dans l'environnement ou dans .env."
            )
    conn = PgConnection(psycopg.connect(url, prepare_threshold=None))
    if migrate:
        migrate_pg(conn)
    return conn
