import { NextResponse } from "next/server";
import { getProvider, ollamaHost, ollamaModel, ollamaVisionModel } from "@/lib/ai";

export const runtime = "nodejs";

interface EngineStatus {
  provider: "ollama" | "anthropic" | "offline";
  model: string;
  visionModel: string;
  ready: boolean;
  detail: string;
  installedModels?: string[];
}

/** "llama3.1" should match an installed "llama3.1:latest". */
function modelMatches(configured: string, installedName: string): boolean {
  if (installedName === configured) return true;
  if (installedName === `${configured}:latest`) return true;
  return false;
}

export async function GET() {
  const provider = getProvider();
  const model = ollamaModel();
  const visionModel = ollamaVisionModel();

  if (provider === "offline") {
    const status: EngineStatus = {
      provider,
      model,
      visionModel,
      ready: true,
      detail: "Running without AI: text files and typed PDFs only; cards are generated by simple rules.",
    };
    return NextResponse.json(status);
  }

  if (provider === "anthropic") {
    const ready = !!process.env.ANTHROPIC_API_KEY;
    const status: EngineStatus = {
      provider,
      model,
      visionModel,
      ready,
      detail: ready
        ? "Connected to Anthropic Claude (cloud)."
        : "ANTHROPIC_API_KEY is not set. Add it to .env or switch AI_PROVIDER to \"ollama\" or \"offline\".",
    };
    return NextResponse.json(status);
  }

  // provider === "ollama"
  const host = ollamaHost();
  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 2500);
    let response: Response;
    try {
      response = await fetch(`${host}/api/tags`, { signal: controller.signal });
    } finally {
      clearTimeout(timeout);
    }

    if (!response.ok) {
      const status: EngineStatus = {
        provider,
        model,
        visionModel,
        ready: false,
        detail: "Ollama isn't running. Install from ollama.com, then run: ollama serve",
      };
      return NextResponse.json(status);
    }

    const data = (await response.json()) as { models?: { name: string }[] };
    const installedModels = (data.models ?? []).map((m) => m.name);
    const hasModel = installedModels.some((name) => modelMatches(model, name));

    const status: EngineStatus = {
      provider,
      model,
      visionModel,
      ready: hasModel,
      detail: hasModel
        ? `Connected to Ollama (${model})`
        : `Ollama is running but the model isn't downloaded. Run: ollama pull ${model}`,
      installedModels,
    };
    return NextResponse.json(status);
  } catch {
    const status: EngineStatus = {
      provider,
      model,
      visionModel,
      ready: false,
      detail: "Ollama isn't running. Install from ollama.com, then run: ollama serve",
    };
    return NextResponse.json(status);
  }
}
